use ripple_reader::extractor::{
    conclusion_match_score, extract_sections, find_next_stop, intro_match_score,
};

#[test]
fn test_intro_match_score_exact() {
    assert_eq!(intro_match_score("1 Introduction"), 1.0);
    assert_eq!(intro_match_score("Introduction"), 1.0);
    assert_eq!(intro_match_score("Background"), 1.0);
    assert_eq!(intro_match_score("Related Work"), 1.0);
}

#[test]
fn test_intro_match_score_partial() {
    assert_eq!(intro_match_score("An introduction to..."), 0.6);
    assert_eq!(intro_match_score("Some background info"), 0.6);
    assert_eq!(intro_match_score("Related work section"), 0.45);
    assert_eq!(intro_match_score("Random title"), 0.0);
}

#[test]
fn test_conclusion_match_score_exact() {
    assert_eq!(conclusion_match_score("Conclusion"), 1.0);
    assert_eq!(conclusion_match_score("5 Conclusions"), 1.0);
    assert_eq!(conclusion_match_score("Discussion"), 1.0);
    assert_eq!(conclusion_match_score("Future Work"), 1.0);
}

#[test]
fn test_conclusion_match_score_partial() {
    assert_eq!(conclusion_match_score("In conclusion"), 0.6);
    assert_eq!(conclusion_match_score("A brief summary"), 0.45);
    assert_eq!(conclusion_match_score("Random text"), 0.0);
}

#[test]
fn test_extract_sections_typical_structure() {
    let text = r#"
Abstract
This is the abstract.

1 Introduction
This is the intro paragraph.
It has multiple lines.

2 Methods
We did some stuff.

3 Results
Great results here.

4 Conclusion
This is the conclusion.
Summary of findings.

References
[1] Some ref
"#;
    let sections = extract_sections(text);
    assert!(sections.intro.contains("Introduction"));
    assert!(sections.intro.contains("This is the intro paragraph"));
    assert!(!sections.intro.contains("Methods"));
    assert!(sections.conclusion.contains("Conclusion"));
    assert!(sections.conclusion.contains("Summary of findings"));
    assert!(!sections.conclusion.contains("References"));
}

#[test]
fn test_extract_sections_no_clear_headers() {
    let text = "\n".repeat(20)
        + "This is just body text without any headers. "
        + "It keeps going for a while to simulate a real document. ";
    let text = text.repeat(20);
    let sections = extract_sections(&text);
    // Should use fallback and return non-empty strings
    assert!(!sections.intro.is_empty());
    assert!(!sections.conclusion.is_empty());
}

#[test]
fn test_find_next_stop() {
    let paragraphs = vec![
        "Introduction".to_string(),
        "Some text".to_string(),
        "Methods".to_string(),
        "More text".to_string(),
    ];
    assert_eq!(find_next_stop(&paragraphs, 1), 2);
    assert_eq!(find_next_stop(&paragraphs, 3), paragraphs.len());
}

#[test]
fn test_extract_sections_conclusion_before_intro() {
    // Regression test: conclusion-like text appears before the real intro,
    // which used to cause a panic because the slice start > end.
    let text = r#"
Discussion
This is an early discussion block.

1 Introduction
This is the real intro.
It has multiple lines.

2 Methods
We did some stuff.

3 Results
Great results here.

4 Conclusion
This is the conclusion.
"#;
    let sections = extract_sections(text);
    assert!(sections.intro.contains("Introduction"));
    assert!(!sections.intro.contains("Discussion"));
    assert!(sections.conclusion.contains("Conclusion"));
    assert!(!sections.conclusion.contains("Methods"));
}

#[test]
fn test_extract_header_multi_author_superscript() {
    // Paper with comma-separated authors and superscript affiliations
    let text = r#"SCOPE: Structured Decomposition and Conditional Skill Orchestration for
Complex Image Generation

Alice Chen1, Bob Wang1, Charlie Li1, Diana Zhang1*, Edward Liu1*,
Fiona Wu1, George Huang1, Helen Zhou1, Ivan Xu1, Julia Yang1, Kevin Sun,
Laura Zhao2,3, Michael Lin1, Nancy He1, Oscar Jiang1, Patricia Shen1†

1MoE Key Laboratory of Intelligent Systems,
Northern Technical University
2Central Lakes University
3Pacific State University
*Project lead.
†Corresponding author.

Project page: https://example.org/project/

Figure 1: Examples generated by the framework across knowledge-intensive events, reference-heavy intellectual properties,
and multi-entity compositions. The framework maintains structured commitments and invokes skills to resolve or repair them
throughout generation, leading to SOTA performance on benchmarks.

1

arXiv:9999.99999v1  [cs.CV]  1 Jan 2020

Abstract

While text-to-image models have made strong
progress in visual fidelity, faithfully realizing
complex visual intents remains challenging
because many requirements must be tracked
across grounding, generation, and verification.
"#;
    let sections = extract_sections(text);
    assert!(
        sections.header.contains("Alice Chen"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Diana Zhang"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Patricia Shen"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Northern Technical University"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Central Lakes University"),
        "header='{}'",
        sections.header
    );
}

#[test]
fn test_extract_header_two_line_title_no_colon() {
    // Paper with two-line title (no colon), authors with email/institution blocks
    let text = r#"Controlling Transient Amplification Improves
Long-horizon Rollouts

David Kim
david.kim@example.edu
Mountain Ridge Research Institute
Springfield, USA

Sarah Park
sarah.park@example.edu
Mountain Ridge Research Institute
Springfield, USA

Abstract

Autoregressive neural simulators now match classical solvers on short-horizon prediction of
physical systems, yet their accuracy degrades rapidly when rolled out over long horizons.
"#;
    let sections = extract_sections(text);
    assert!(
        sections.header.contains("David Kim"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Sarah Park"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections
            .header
            .contains("Mountain Ridge Research Institute"),
        "header='{}'",
        sections.header
    );
}

#[test]
fn test_extract_header_single_line_author() {
    // Paper with one author per line, no commas
    let text = r#"Embeddings for Preferences, Not Semantics∗

James Wilson
Oakwood University
james.wilson@example.edu

Emily Davis
Oakwood University
emily.davis@example.edu

Robert Taylor
Oakwood University
robert.taylor@example.edu

Abstract

Modern AI is opening the door to collective decision-making in which participants
express their views as free-form text rather than voting on a fixed set of candidates.
"#;
    let sections = extract_sections(text);
    assert!(
        sections.header.contains("James Wilson"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Emily Davis"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Robert Taylor"),
        "header='{}'",
        sections.header
    );
    assert!(
        sections.header.contains("Oakwood University"),
        "header='{}'",
        sections.header
    );
}
